# Generated by Django 4.2.2 on 2023-07-03 10:19

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_type', models.CharField(blank=True, choices=[('D', 'Doctor'), ('N', 'Nurses'), ('A', 'Asha Worker'), ('O', 'Other')], max_length=1, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=functools.partial(Users.models.get_unique_profile_pic_name, *(), **{}))),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_profile_ids',
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=functools.partial(Users.models.get_unique_profile_pic_name, *(), **{}))),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('tester_type', models.CharField(blank=True, max_length=1, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_id', models.ForeignKey(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.professionalprofile')),
                ('user_id', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_personal_profile_ids',
            },
        ),
    ]
