# Generated by Django 4.2.2 on 2023-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Personal'), ('MR', 'Professional'), ('B', 'Both')], default='P', max_length=2, null=True),
        ),
    ]
