# Generated by Django 4.2.2 on 2023-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_professionalprofile_personalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(blank=True, choices=[('P', 'Personal'), ('MR', 'Professional'), ('B', 'Both')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Blocked')], default='A', max_length=1, null=True),
        ),
    ]
