# Generated by Django 4.2.2 on 2023-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='tester_type',
            field=models.CharField(blank=True, default=1, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[(0, 'Doctor'), (1, 'Nurses'), (2, 'Asha Worker'), (3, 'Other')], max_length=1, null=True),
        ),
    ]
