# Generated by Django 4.2.2 on 2023-07-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_personalprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='gender',
        ),
    ]
