# Generated by Django 4.2.2 on 2023-07-13 09:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'delete_account_request',
            },
        ),
    ]
