# Generated by Django 4.2.2 on 2023-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteaccountrequests',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
