# Generated by Django 4.2.2 on 2023-07-04 13:41

import AppGluco.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_users_type_alter_users_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to=functools.partial(AppGluco.models.get_unique_profile_video, *(), **{}))),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_id', models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='Users.personalprofile')),
            ],
            options={
                'db_table': 'video_table',
            },
        ),
        migrations.CreateModel(
            name='GlucoResultTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gluco_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reported_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient_id', models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='Users.personalprofile')),
                ('profile_id', models.ForeignKey(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.professionalprofile')),
                ('video_location', models.ForeignKey(db_column='video', on_delete=django.db.models.deletion.CASCADE, to='AppGluco.videotable')),
            ],
            options={
                'db_table': 'gluco_result_table',
            },
        ),
    ]
