# Generated by Django 4.2.2 on 2023-07-07 09:52

import AppGluco.models
import AppGluco.validator
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoResultTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gluco_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reported_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'gluco_result_table',
            },
        ),
        migrations.CreateModel(
            name='VideoTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to=functools.partial(AppGluco.models.get_unique_profile_video, *(), **{}), validators=[AppGluco.validator.validate_file_extension])),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'video_table',
            },
        ),
    ]
