# Generated by Django 4.2.2 on 2023-07-06 06:27

import AppGluco.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('AppGluco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotable',
            name='video_file',
            field=models.FileField(upload_to=functools.partial(AppGluco.models.get_unique_profile_video, *(), **{}), validators=[AppGluco.models.validate_file_extension]),
        ),
    ]
