# Generated by Django 4.2.2 on 2023-07-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('AppGluco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotable',
            name='profile_id',
            field=models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='Users.personalprofile'),
        ),
        migrations.AddField(
            model_name='glucoresulttable',
            name='patient_id',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to='Users.personalprofile'),
        ),
        migrations.AddField(
            model_name='glucoresulttable',
            name='profile_id',
            field=models.ForeignKey(blank=True, db_column='profile', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.professionalprofile'),
        ),
        migrations.AddField(
            model_name='glucoresulttable',
            name='video_location',
            field=models.ForeignKey(db_column='video', on_delete=django.db.models.deletion.CASCADE, to='AppGluco.videotable'),
        ),
    ]
