# Generated by Django 4.2.2 on 2023-08-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGluco', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'FAQ_table',
            },
        ),
    ]
